-- TABLES DDL
CREATE TABLE PRODUCTS (
     ID NUMBER,
     NAME VARCHAR2(50),
     INVENTORY_COUNT NUMBER(10),
     UNIT_PRICE NUMBER(*,2),
     PRIMARY KEY(ID)
);

CREATE TABLE ORDERS (
     ID NUMBER,
     CUSTOMER_NAME VARCHAR2(50),
     QUANTITY NUMBER(10),
     ORDER_PRICE NUMBER(*,2),
     TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     PRIMARY KEY(ID),
     FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)    
);

CREATE TABLE AUDIT_PRODUCTS (
     ID NUMBER,
     UNIT_PRICE NUMBER(*,2),
     INVENTORY_COUNT NUMBER(10),
     INVENTORY_CHANGE NUMBER(10),
     REVISION_TYPE NCHAR(6),
     REVISION_TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID)
);

-- SEQUENCES DDL
CREATE SEQUENCE SEQ_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ORDERS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AUDIT_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

-- TRIGGER FOR INPUTING TOTAL ORDER PRICE AND ITS TIMESTAMP
CREATE OR REPLACE TRIGGER ORDER_PRICE_TRIGGER 
    BEFORE 
    INSERT OR UPDATE
    ON ORDERS
    FOR EACH ROW
DECLARE
    PRICE NUMBER(20,2);
BEGIN
    SELECT UNIT_PRICE
    INTO PRICE
    FROM PRODUCTS
    WHERE PRODUCTS.ID = :NEW.PRODUCT_ID;
    
    :NEW.ORDER_PRICE := :NEW.QUANTITY * PRICE;
    
    :NEW.TSTMP := CURRENT_TIMESTAMP;
END;