-- DBA
--CREATE USER C##AL IDENTIFIED BY AL;
--GRANT DBA TO C##AL;

-- TABLES DDL
CREATE TABLE PRODUCTS (
     ID NUMBER,
     NAME VARCHAR2(50),
     INVENTORY_COUNT NUMBER(10),
     UNIT_PRICE NUMBER(*,2),
     PRIMARY KEY(ID)
);

CREATE TABLE AUDIT_PRODUCTS (
     ID NUMBER,
     NAME VARCHAR2(50),
     UNIT_PRICE NUMBER(*,2),
     INVENTORY_COUNT NUMBER(10),
     INVENTORY_CHANGE NUMBER(10),
     REVISION_TYPE VARCHAR2(6),
     REVISION_TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     PRIMARY KEY(ID)
);

CREATE TABLE ORDERS (
     ID NUMBER,
     CUSTOMER_NAME VARCHAR2(50),
     QUANTITY NUMBER(10),
     ORDER_PRICE NUMBER(*,2),
     TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     PRIMARY KEY(ID)
);

-- SEQUENCES DDL
CREATE SEQUENCE SEQ_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ORDERS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_AUDIT_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

-- APP USER
CREATE USER C##APP_USER IDENTIFIED BY APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCTS TO C##APP_USER;
GRANT SELECT, INSERT ON AUDIT_PRODUCTS TO C##APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ORDERS TO C##APP_USER;


