-- STATEMENT-LEVEL TRIGGER FOR ENSURING ORDERS CAN ONLY BE CREATED OR MANIPULATED DURING BUSINESS HOURS
CREATE OR REPLACE TRIGGER BUSINESS_HOURS_TRIGGER
  BEFORE 
  INSERT OR UPDATE OR DELETE
  ON ORDERS
DECLARE
  -- TRIGGER VARIABLES	
  DAY_OF_WEEK CHAR;
  HOUR_OF_DAY NUMBER(2);
  -- EXCEPTION
  OUTSIDE_OF_HOURS EXCEPTION;
  PRAGMA EXCEPTION_INIT(OUTSIDE_OF_HOURS, -20001); -- PRAGMA MEANS COMPILER DIRECTIVE AND IS USED IN THIS CASE TO BIND NEWLY CREATED 
  												   -- OUTSIDE_OF_HOURS EXCEPTION T0 THE ERROR CODE -20002; CODE MUST BE BTW. -20001 AND -20999
BEGIN
  -- INITIALIZE DAY_OF_WEEK SO THAT IT CORRESPONDS TO TODAY		
  SELECT TO_CHAR(SYSDATE, 'D')
  INTO DAY_OF_WEEK
  FROM DUAL;
  -- INITIALIZE HOUR_OF_DAY SO THAT IT CORRESPONDS TO THE CURRENT HOUR
  SELECT EXTRACT(HOUR FROM CURRENT_TIMESTAMP)
  INTO HOUR_OF_DAY
  FROM DUAL;
  -- CHECK TO SEE IF TODAY IS SUNDAY OR SATURDAY	
  IF DAY_OF_WEEK = '1' OR DAY_OF_WEEK = '7' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Cannot place order on weekends');
  END IF;
  -- CHECK TO SEE IF THE CURRENT HOUR IS OUTSIDE OF THE BUSINESS HOURS (9:00 AM TO 5:00 PM)  
  IF HOUR_OF_DAY < 12 OR HOUR_OF_DAY > 21 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Cannot place order outside of business hours');
  END IF;
END;
/