-- ROW-LEVEL TRIGGER FOR AUDTING THE PRODUCTS TABLE
CREATE OR REPLACE TRIGGER PRODUCTS_AUDIT_TRIGGER
  AFTER
  INSERT OR UPDATE OR DELETE
  ON PRODUCTS
  FOR EACH ROW
BEGIN
  CASE
    WHEN INSERTING THEN
      -- INSERT A ROW INTO THE AUDIT_PRODUCTS TABLE WITH ALL THE NEW VALUES	
      INSERT INTO AUDIT_PRODUCTS VALUES (SEQ_AUDIT_PRODUCTS_ID.NEXTVAL,
        :NEW.NAME, :NEW.UNIT_PRICE, :NEW.INVENTORY_COUNT,
        :NEW.INVENTORY_COUNT, 'INSERT', CURRENT_TIMESTAMP, :NEW.ID);
    WHEN UPDATING THEN
      -- INSERT A ROW INTO THE AUDIT_PRODUCTS TABLE WITH THE NEW VALUES EXECPT FOR THE INVENTORY_CHANGE COLUMN;
      -- IT GETS POPULATED WITH THE DIFFERENCE BETWEEN THE NEW INVENTORY_COUNT AND OLD INVENTORY_COUNT
      INSERT INTO AUDIT_PRODUCTS VALUES (SEQ_AUDIT_PRODUCTS_ID.NEXTVAL,
        :NEW.NAME, :NEW.UNIT_PRICE, :NEW.INVENTORY_COUNT,
        :NEW.INVENTORY_COUNT - :OLD.INVENTORY_COUNT, 'UPDATE', 
        CURRENT_TIMESTAMP, :NEW.ID);
    WHEN DELETING THEN
      -- INSERT A ROW INTO THE AUDIT_PRODUCTS TABLE WITH THE OLD VALUES EXECPT FOR THE INVENTORY_CHANGE COLUMN;
      -- IT GETS POPULATED WITH THE VALUE 0	
      INSERT INTO AUDIT_PRODUCTS VALUES (SEQ_AUDIT_PRODUCTS_ID.NEXTVAL,
        :OLD.NAME, :OLD.UNIT_PRICE, :OLD.INVENTORY_COUNT, 0, 'DELETE', 
        CURRENT_TIMESTAMP, :OLD.ID);
  END CASE;
END;
/
