--CREATE DBA
CREATE USER C##AL IDENTIFIED BY AL;
GRANT DBA TO C##AL;

-- TABLES DDL
CREATE TABLE C##AL.PRODUCTS (
     ID NUMBER,
     NAME VARCHAR2(50),
     INVENTORY_COUNT NUMBER(10),
     UNIT_PRICE NUMBER(*,2),
     PRIMARY KEY(ID)
);

CREATE TABLE C##AL.AUDIT_PRODUCTS (
     ID NUMBER,
     NAME VARCHAR2(50),
     UNIT_PRICE NUMBER(*,2),
     INVENTORY_COUNT NUMBER(10),
     INVENTORY_CHANGE NUMBER(10),
     REVISION_TYPE VARCHAR2(6),
     REVISION_TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     PRIMARY KEY(ID)
);

CREATE TABLE C##AL.ORDERS (
     ID NUMBER,
     CUSTOMER_NAME VARCHAR2(50),
     QUANTITY NUMBER(10),
     ORDER_PRICE NUMBER(*,2),
     TSTMP TIMESTAMP,
     PRODUCT_ID NUMBER,
     PRIMARY KEY(ID)
);

-- SEQUENCES DDL
CREATE SEQUENCE C##AL.SEQ_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE C##AL.SEQ_ORDERS_ID START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE C##AL.SEQ_AUDIT_PRODUCTS_ID START WITH 1 INCREMENT BY 1;

--CREATE APP'S USER ACCT.
CREATE USER C##APP_USER IDENTIFIED BY APP;
GRANT CREATE SESSION TO C##APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON C##AL.PRODUCTS TO C##APP_USER;
GRANT SELECT, INSERT ON C##AL.AUDIT_PRODUCTS TO C##APP_USER;	--USER CANNOT CREATE A PRODUCT
GRANT SELECT, INSERT, UPDATE, DELETE ON C##AL.ORDERS TO C##APP_USER;
GRANT SELECT ON C##AL.SEQ_ORDERS_ID TO C##APP_USER;
GRANT SELECT ON C##AL.SEQ_PRODUCTS_ID TO C##APP_USER;
GRANT SELECT ON C##AL.SEQ_AUDIT_PRODUCTS_ID TO C##APP_USER;
