INSERT INTO C##AL.PRODUCTS VALUES (C##AL.SEQ_PRODUCTS_ID.NEXTVAL, 'Widget', 1000, 1.25);
INSERT INTO C##AL.PRODUCTS VALUES (C##AL.SEQ_PRODUCTS_ID.NEXTVAL, 'Samsung 970 Pro SSD', 500, 219.95);
INSERT INTO C##AL.PRODUCTS VALUES (C##AL.SEQ_PRODUCTS_ID.NEXTVAL, 'Intel Xeon Processor', 200, 499.99);
INSERT INTO C##AL.PRODUCTS VALUES (C##AL.SEQ_PRODUCTS_ID.NEXTVAL, 'Keyboard', 2000, 25.00);

ALTER TRIGGER C##AL.BUSINESS_HOURS_TRIGGER DISABLE;

INSERT INTO C##AL.ORDERS (ID, CUSTOMER_NAME, PRODUCT_ID, QUANTITY) VALUES (C##AL.SEQ_ORDERS_ID.NEXTVAL, 'John Wayne', 3, 75);

ALTER TRIGGER C##AL.BUSINESS_HOURS_TRIGGER ENABLE;

COMMIT;